name: Build Pull Request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build with Maven
        run: mvn -B package -T 2C
      - name: Archive artifacts (Rory Standalone)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Rory Standalone
          path: bootstrap/standalone/target/Rory.jar
      - name: Archive artifacts (Rory Spigot)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Rory Spigot
          path: bootstrap/spigot/target/Rory-Spigot.jar
      - name: Archive artifacts (Rory BungeeCord)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Rory BungeeCord
          path: bootstrap/bungeecord/target/Rory-BungeeCord.jar
      - name: Archive artifacts (Rory Sponge)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Rory Sponge
          path: bootstrap/sponge/target/Rory-Sponge.jar
      - name: Archive artifacts (Rory Velocity)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Rory Velocity
          path: bootstrap/velocity/target/Rory-Velocity.jar
